---
title: "Oregon Surf"
author: "Ken W."
date: "9/13/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(rvest)
library(tidyverse)
library(leaflet)

```

## [Station 46050 (LLNR 641) - STONEWALL BANK - 20NM West of Newport, OR](https://www.ndbc.noaa.gov/station_page.php?station=46050)



```{r echo=FALSE}

station <- "46029"
noaa_url <- read_html(paste0("https://www.ndbc.noaa.gov/station_page.php?station=", station))

# Get the lat/long
noaa_lat_lng <- noaa_url %>%
  html_nodes("#stn_metadata p b") %>%
  .[[4]] %>%
  html_text()

noaa_lat <- as.numeric(str_split(noaa_lat_lng, " ")[[1]][1])
noaa_lng <- as.numeric(str_split(noaa_lat_lng, " ")[[1]][3]) * -1
  
# Get the data
noaa <- noaa_url %>%
  html_node("#contenttable td#contentarea table.dataTable") %>%
  html_table() 

wvht_obvs <- gsub("-",NA,noaa[-1,7])

wave_max = max(as.numeric(wvht_obvs), na.rm = TRUE)
wave_min = min(as.numeric(wvht_obvs), na.rm = TRUE)
wave_avg = mean(as.numeric(wvht_obvs), na.rm = TRUE)

content <- paste0(
  "<strong>NOAA Buoy #", station, " - 20NM West of Newport, OR</strong></br>",
  "<pre>",
  "Min: ", wave_min, "ft\n",
  "Max: ", wave_max, "ft\n",
  "Avg: ", round(wave_avg), "ft\n",
  "</pre>"
)

leaflet() %>% 
  setView(noaa_lng, noaa_lat, zoom = 9) %>%
  addTiles() %>%
  addPopups(noaa_lng, noaa_lat, content, 
            options = popupOptions(closeButton = FALSE))

```

